# -*- coding: utf-8 -*-
"""EmployeeGen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11xZGxDeJtWiXobHU-FuNYvDkP-ijR_hb
"""

!pip install passlib

import passlib
from passlib.hash import pbkdf2_sha512

class Employee:
    """The employee class is intended to automate and streamline the account creation of new company team members"""
    def __init__(self, full_name, age):
      self.full_name = full_name
      self.age = age

    def add_salary(self, pay):
      self.salary = pay
    
    def create_password(self, passphrase):
      self.key = pbkdf2_sha512.hash(passphrase)

person1 = Employee("John Smith", 27)

person1.add_salary(62000)

person1.create_password(input("Please enter a password: "))

print(person1.key)

def menu():
  print("1) Display Employee Name \n2) Display Employee Age \n3) Display Employee Salary \n4)Display Employee Key WARNING EMPLOYEE PASSWORD")
  choice = input()
  try:
    if (choice == "1"):
      print(person1.full_name)
    elif (choice == "2"):
      print(person1.age)
    elif (choice == "3"):
      print(person1.salary)
    elif (choice == "4"):
      print(person1.key)
  except:
    print("Something went wrong!")

menu()